<div class="container">
    <div class="row vertical-offset-100">
        <div class="col-sm-6 col-sm-offset-3 col-md-5 col-md-offset-4 col-lg-4 col-lg-offset-4">
            <div id="container_demo">
                <div id="wrapper">
                    <div id="login" class="animate form">
                        <?php if (count($this->messages) > 0): ?>
                            <div class="alert alert-danger alert-dismissable" style="margin-top: 10px">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <?=$this->messages[0];?>
                            </div>

                        <?php endif; ?>
                        <h3 class="login_bg">
                            <img src="/images/Logo114x114.png" alt="clinik logo">
                        </h3>
                        <?=$this->form->render()?>
                        <p>
                            <?=$this->LangSelector();?>
                        </p>
                   </div>
                </div>
            </div>
        </div>
    </div>
</div>