<?php if ($this->errors) : ?>

	<div class="container">
		<div class="row vertical-offset-100">
			<div class="col-sm-6 col-sm-offset-3  col-md-5 col-md-offset-4 col-lg-4 col-lg-offset-4">
				<div id="container_demo">
					<div id="wrapper">
						<div id="login" class="animate form">

							<h3 class="login_bg">
								<img src="/images/Logo114x114.png" alt="clinik logo">
							</h3>
							<?=$this->form->render()?>
							<p>

							</p>


						</div>

					</div>
				</div>
			</div>
		</div>
	</div>


<?php endif;?>