<div class="modal fade in" id="newtreatment" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title"><?=$this->translate(gettext("New Treatment"));?></h4>
            </div>
            <div class="modal-body">
                <div class="row" id="new-treatment-modal-lang">
                    <div class="col-md-12">
                        <h4><?=$this->translate(gettext("Type"));?></h4>
                        <p>
                            <select id="type_fr" name="type_fr" class="form-control select2" placeholder="<?=$this->translate(gettext("Click to select"));?>">
                                <option value=""></option>
                                <option value="<?=$this->translate(gettext("FACE"));?>"><?=$this->translate(gettext("FACE"));?></option>
                                <option value="<?=$this->translate(gettext("ARM"));?>"><?=$this->translate(gettext("ARM"));?></option>
                                <option value="<?=$this->translate(gettext("DOS/CHEST"));?>"><?=$this->translate(gettext("DOS/CHEST"));?></option>
                                <option value="<?=$this->translate(gettext("THIGH/LEG/FOOT/PUBIS"));?>"><?=$this->translate(gettext("THIGH/LEG/FOOT/PUBIS"));?></option>
                            </select>
                        </p>

                    <h4><?=$this->translate(gettext("French"));?></h4>
                        <p>
                            <input id="description_fr" name="description_fr" type="text" placeholder="<?=$this->translate(gettext("Description"));?>" class="form-control">
                        </p>


                        <h4><?=$this->translate(gettext("English"));?></h4>
                        <p>
                            <input id="description_en" name="description_en" type="text" placeholder="<?=$this->translate(gettext("Description"));?>" class="form-control">
                        </p>


                        <h4><?=$this->translate(gettext("German"));?></h4>
                        
                        <p>
                            <input id="description_de" name="description_de" type="text" placeholder="<?=$this->translate(gettext("Description"));?>" class="form-control">
                        </p>

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn"><?=$this->translate(gettext("Close"));?></button>
                <button type="button" id="save-treatment" class="btn btn-primary"><?=$this->translate(gettext("Save"));?></button>
            </div>
        </div>
    </div>
</div>



