<div class="modal fade in" id="new-questions-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title"><i class="fa fa-th-list"></i> <?=$this->translate(gettext("New Question"));?></h4>
            </div>
            <div class="modal-body">
                <div class="row" id="new-questions-modal-lang">
                    <div class="col-md-12">
                        <div class="form-group">
                            <h4><?=$this->translate(gettext("Group"))?></h4>
                            <div class="checkbox">
                                <label>
                                    <input type="hidden" name="newGroupQuestions" value="0">
                                    <input type="checkbox" name="newGroupQuestions" id="newGroupQuestions" value="1"><?=$this->translate(gettext("New Group?"));?>
                                </label>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn"><?=$this->translate(gettext("Close"));?></button>
                <button type="button" data-dismiss="modal" id="save-treatment" class="btn btn-primary" onclick="sendTreatmentDB('<?=$this->lang?>')"><?=$this->translate(gettext("Save"));?></button>
            </div>
        </div>
    </div>
</div>