<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Clinik <?=ucfirst($this->Clinikname());?></title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <script src="//console.re/connector.js" data-channel="64d4-f8d9-562c" id="consolerescript"></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <!-- global css -->
    <link href="/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- font Awesome -->
    <link href="/vendors/font-awesome-4.6.1/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="/css/styles/black.css" rel="stylesheet" type="text/css" id="colorscheme" />
    <link href="/css/panel.css" rel="stylesheet" type="text/css"/>
    <link href="/css/pages/tables.css" rel="stylesheet" type="text/css"/>
    <link href="/css/metisMenu.css" rel="stylesheet" type="text/css"/>
    <link href="/vendors/daterangepicker/css/daterangepicker-bs3.css" rel="stylesheet" type="text/css" />
    <!--select css-->
    <link href="/vendors/select2/select2.css" rel="stylesheet" />
    <link rel="stylesheet" href="/vendors/select2/select2-bootstrap.css" />
    <!--clock face css-->
    <link href="/vendors/iCheck/skins/all.css" rel="stylesheet" />
    <link href="/css/pages/formelements.css" rel="stylesheet" />
    <link href="/vendors/modal/css/component.css" rel="stylesheet" />

    <link rel="stylesheet" href="/css/custom/styles.css" />
</head>

<body class="skin-josh">
<header class="header">
    <div class="logo">
        <span class="RPS_Clinik_Title">Clinik - <?=ucfirst($this->Clinikname());?></span>
    </div>
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->

        <div class="navbar-right">
            <ul class="nav navbar-nav">
                <?php if($this->Admin()): ?>
                <li class="dropdown messages-menu" style="padding-right: 20px;">
                    <a href="/admin">
                        <i class="livicon" data-name="gears" data-size="28" data-color="#ffffff" data-hovercolor="#ffffff"></i>
                    </a>
                </li>
                <?php endif; ?>
            <li class="dropdown messages-menu" style="padding-right: 20px;">
                <a href="/logout">
                    <i class="livicon" data-name="sign-in" data-size="28" data-color="#ffffff" data-hovercolor="#ffffff"></i>
                </a>
            </li>
            </ul>
        </div>
    </nav>
</header>
<div class="wrapper row-offcanvas row-offcanvas-left">

    <aside class="">
        <!-- Main content -->
        <section class="content-header">
            <ol class="breadcrumb">
                <li class="active">
                    <a href="/clinic">
                        <i class="livicon" data-name="home" data-size="16" data-color="#333" data-hovercolor="#333"></i>
                        Home
                    </a>
                </li>
                    <li><a href="/clients/dashboard/<?=$this->ClientID()?>"><?=$this->Client()?></a></li>
                    <input type="hidden" id="hidden_client_id" value="<?=$this->ClientID()?>">
            </ol>

        </section>
        <section class="content">
            <?php echo $this->layout()->content; ?>
            <!--/row-->

            <div class="clearfix"></div>


        </section>
    </aside>
    <!-- right-side -->
</div>

<!-- global js -->
<script src="/js/jquery-2.2.3.min.js" type="text/javascript"></script>
<script src="/js/bootstrap.min.js" type="text/javascript"></script>
<!--livicons-->
<script src="/vendors/livicons/minified/raphael-min.js" type="text/javascript"></script>
<script src="/vendors/livicons/minified/livicons-1.4.min.js" type="text/javascript"></script>
<script src="/js/josh.js" type="text/javascript"></script>
<script src="/js/metisMenu.js" type="text/javascript"> </script>
<script src="/vendors/holder-master/holder.js" type="text/javascript"></script>
<!-- end of global js -->


<!-- Back to Top-->
<script type="text/javascript" src="/vendors/countUp/countUp.js"></script>


<script src="/vendors/input-mask/jquery.inputmask.js" type="text/javascript"></script>
<script src="/vendors/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
<script src="/vendors/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
<script src="/vendors/daterangepicker/daterangepicker.js" type="text/javascript"></script>
<script src="/vendors/select2/select2.js" type="text/javascript"></script>
<script src="/vendors/iCheck/icheck.js" type="text/javascript"></script>
<script src="/vendors/autogrow/js/jQuery-autogrow.js" type="text/javascript"></script>
<script src="/vendors/maxlength/bootstrap-maxlength.min.js" type="text/javascript"></script>
<script src="/vendors/card/jquery.card.js" type="text/javascript"></script>
<script src="/js/pages/formelements.js" type="text/javascript"></script>
<script src="/vendors/modal/js/classie.js"></script>
<script src="/vendors/modal/js/modalEffects.js"></script>
<script src="/js/custom/common.js"></script>

<?=$this->JSHelper(); ?>
<?php echo $this->inlineScript(); ?>
</body>
</html>
