<!DOCTYPE html>
<html>

<head>
    <title>Login | Clinik</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- global level css -->
    <link href="/css/bootstrap.min.css" rel="stylesheet" />
    <!-- end of global level css -->
    <!-- page level css -->
    <link rel="stylesheet" type="text/css" href="/css/pages/login.css" />
    <!-- end of page level css -->
    <link rel="stylesheet" type="text/css" href="/css/custom/styles.css" />
</head>

<body>
<?php echo $this->layout()->content; ?>
<!-- global js -->
<script src="/js/jquery-1.11.3.min.js" type="text/javascript"></script>
<!-- Bootstrap -->
<script src="/js/bootstrap.min.js" type="text/javascript"></script>
<!--livicons-->
<script src="/vendors/livicons/minified/raphael-min.js" type="text/javascript"></script>
<script src="/vendors/livicons/minified/livicons-1.4.min.js" type="text/javascript"></script>
<script src="/js/josh.js" type="text/javascript"></script>
<script src="/js/metisMenu.js" type="text/javascript"> </script>
<script src="/vendors/holder-master/holder.js" type="text/javascript"></script>
<!-- end of global js -->
<?=$this->JSHelper(); ?>
</body>
</html>