<?php if ($this->errors) : ?>

	<div class="row">
		<div class="col-lg-6 margin_10 animated fadeInLeftBig rps_margin_left_40">
			<div class="panel panel-default" id="hidepanel1">
				<div class="panel-heading">
					<h3 class="panel-title">
						<i class="fa fa-user" style="width: 16px; height: 16px;"></i>
						<?=$this->translate(gettext("New Client"));?>
					</h3>

				</div>
				<div class="panel-body">
					<fieldset>
						<?=$this->form; ?>
					</fieldset>
				</div>
			</div>
		</div>
	</div>


<?php endif;?>