<?php if (count($this->messages) > 0): ?>
<div class="row">
	<div class="col-lg-6 margin_10 animated fadeInLeftBig rps_margin_left_40">
		<div class="alert alert-danger alert-dismissable" style="margin-top: 10px">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
			<?=$this->messages[0];?>
		</div>
	</div>
</div>
<?php endif; ?>
<div class="row">
	<div class="col-lg-6 margin_10 animated fadeInLeftBig rps_margin_left_40">
		<div class="panel panel-default" id="hidepanel1">
			<div class="panel-heading">
				<h3 class="panel-title">
					<i class="fa fa-user" style="width: 16px; height: 16px;"></i>
					<?=$this->translate(gettext("Search for Client"));?>
				</h3>

			</div>
			<div class="panel-body">
				<fieldset>
					<form id="Search_for_Client"  enctype="application/x-www-form-urlencoded" role="form" action="/clients/clients/searchfor" method="post">

						<div class="form-group">
							<label><?=$this->translate(gettext("Search for:"));?></label>
							<!--<div class="radio">
								<label>
									<input type="radio" name="optionsRadios" id="optionsRadios1" value="option1"><?/*=$this->translate(gettext("Email"));*/?>
								</label>
							</div>-->
							<!-- For another version maybe
							<div class="radio">
								<label>
									<input type="radio" name="optionsRadios" id="optionsRadios2" value="option2"><?=$this->translate(gettext("Birthdate"));?>
								</label>
							</div>
							<div class="radio">
								<label>
									<input type="radio" name="optionsRadios" id="optionsRadios3" value="option3"><?=$this->translate(gettext("Mobile"));?>
								</label>
							</div>
							<div class="radio">
								<label>
									<input type="radio" name="optionsRadios" id="optionsRadios4" value="option4"><?=$this->translate(gettext("Phone"));?>
								</label>
							</div>
							-->
							<div class="radio">
								<label>
									<input type="radio" name="optionsRadios" id="optionsRadios5" value="option5" checked="checked"><?=$this->translate(gettext("First Name + Last Name"));?>
								</label>
							</div>
							<div class="form-group input-group">
								<span class="input-group-addon"><i class="fa fa-search"></i></span>
								<input type="text" id="rps_text_search_client" name="rps_text_search_client" class="form-control" >
							</div>
						</div>
						<div class="form-group">
							<div class="col-md-12 text-right">
								<button type="submit" id="rps_submit_search_client_button" class="btn btn-responsive btn-primary btn-sm"><?=$this->translate(gettext("Search"));?></button>
							</div>
						</div>

					</form>

				</fieldset>
			</div>
		</div>
	</div>
</div>