<?php if (count($this->results >0 )) : ?>

<div class="row">
	<div class="col-lg-12 margin_10">
	<table class="table table-striped table-bordered table-advance table-hover">
		<thead>
			<tr>
				<th>
					<i class="fa fa-user"></i>
					<?=$this->translate(gettext("Nom"))?>
				</th>
				<!--<th>
					<i class="fa fa-envelope"></i>
					<?/*=$this->translate(gettext("Email"))*/?>
				</th>-->
				<th>
					<i class="fa fa-mobile-phone"></i>
					<?=$this->translate(gettext("Age"))?>
				</th>
				<th>
					<i class="fa fa-phone"></i>
					<?=$this->translate(gettext("Origin"))?>
				</th>

				<th>
					<i class="fa fa-eye"></i>
					<?=$this->translate(gettext("Select"))?>
				</th>
			</tr>
		</thead>
		<tbody>

		<?php foreach ($this->results as $result):?>
			<tr>
				<td><?=$this->escape($result["first_name"] . " " . $result["last_name"]);?></td>
				<!--<td><?/*=$this->escape($result["email"]);*/?></td>-->
				<td><?=$this->escape($result["age"]);?></td>
				<td><?=$this->escape($result["origin"]);?></td>
				<td><a href="/clients/dashboard/<?=$this->escape($result["id"]);?>" class="btn default btn-xs red-stripe"><?=$this->translate(gettext("Select"))?></a></td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
</div>
	</div>

<?php else: ?>






<?php endif; ?>
