<div class="md-modal md-effect-1" id="modal-1" style="width: 300px">
    <div class="md-content md-content-red" style="width: 300px">
        <h3 style="color: white"><i class="fa fa-exclamation-triangle"></i> <?=$this->translate(gettext("Attention"));?></h3>
        <div>
        <ul class="RPS-UL">
            <li>
                <?=$this->translate(gettext("Make a TEST 24H to people who have more than 45 years and do 2 joules below the basic skin type!"));?>
            </li>
            <li>
                <?=$this->translate(gettext("If the patient is of Latin origin (Italian, Portuguese, Spanish, Maghrebian, South American), make 2 joules below the basic skin type!"));?>
            </li>
        </ul>
        <br>
        <button class="btn btn-modal btn-default"><?=$this->translate(gettext("Close"));?></button>
    </div>
</div>

<div class="md-modal md-effect-1 col-md-4" id="modal-1a">
    <div class="md-content md-content-red">
        <h3 style="color: white"><i class="fa fa-exclamation-triangle"></i> <?=$this->translate(gettext("Attention"));?></h3>
        <div>
        <ul class="RPS-UL">
            <li>
                <?=$this->translate(gettext("For this Patient make a 24H TEST"));?>
            </li>
        </ul>
        <br>
        <button class="btn btn-modal btn-default" onclick="closeModal('modal-1a')"><?=$this->translate(gettext("Close"));?></button>
    </div>
</div>

<div class="md-modal md-effect-1 col-md-2" id="modal-2">
    <div class="md-content md-content-red">
        <h3 style="color: white"><i class="fa fa-exclamation-triangle"></i> <?=$this->translate(gettext("Attention"));?></h3>
        <div>
        <ul class="RPS-UL">
            <li>
                <?=$this->translate(gettext("If phototype is 4, make a 24H test, test of 6, 8, 10 joule!"));?>
            </li>
        </ul>
        <br>
        <button class="btn btn-modal btn-default"><?=$this->translate(gettext("Close"));?></button>
    </div>
</div>


<div class="md-modal md-effect-1 col-md-2" id="modal-3">
    <div class="md-content md-content-red">
        <h3 style="color: white"><i class="fa fa-exclamation-triangle"></i> <?=$this->translate(gettext("Attention"));?></h3>
        <div
        <ul class="RPS-UL">
            <li>
                <?=$this->translate(gettext("After an exposure to the sun, wait 30 days before begin the treatment"));?>
            </li>
        </ul>
        <br>
        <button class="btn btn-modal btn-default"><?=$this->translate(gettext("Close"));?></button>
    </div>
</div>


<div class="md-modal md-effect-1 col-md-2" id="modal-4">
    <div class="md-content md-content-red">
        <h3 style="color: white"><i class="fa fa-exclamation-triangle"></i> <?=$this->translate(gettext("Attention"));?></h3>
        <div>
        <ul class="RPS-UL">
            <li>
                <?=$this->translate(gettext("If 'YES', wait one month before the next session!"));?>
            </li>
        </ul>
        <br>
        <button class="btn btn-modal btn-default"><?=$this->translate(gettext("Close"));?></button>
    </div>
</div>


<div class="md-modal md-effect-1 col-md-2" id="modal-5">
    <div class="md-content md-content-red">
        <h3 style="color: white"><i class="fa fa-exclamation-triangle"></i> <?=$this->translate(gettext("Attention"));?></h3>
        <div>
            <ul class="RPS-UL">
            <li>
                <?=$this->translate(gettext("Treatment of acne (wait one year after treatment)"));?>
            </li>
            <li>
                <?=$this->translate(gettext(" If antidepressants, taken by medical prescription, make a 24-H test"));?>
            </li>
        </ul>
        <br>
        <button class="btn btn-modal btn-default"><?=$this->translate(gettext("Close"));?></button>
    </div>
</div>

<div class="md-modal md-effect-1 col-md-2" id="modal-6">
    <div class="md-content md-content-red">
        <h3 style="color: white"><i class="fa fa-exclamation-triangle"></i> <?=$this->translate(gettext("Attention"));?></h3>
        <div>
            <ul class="RPS-UL">
            <li>
                <?=$this->translate(gettext("Do a 24H test if the patient use hormone therapy!"));?>
            </li>
        </ul>
        <br>
        <button class="btn btn-modal btn-default"><?=$this->translate(gettext("Close"));?></button>
    </div>
</div>

<div class="md-modal md-effect-1 col-md-2" id="modal-7">
    <div class="md-content md-content-red">
        <h3 style="color: white"><i class="fa fa-exclamation-triangle"></i> <?=$this->translate(gettext("Attention"));?></h3>
        <div>
            <ul class="RPS-UL">
            <li>
                <?=$this->translate(gettext("Do a 24H test if the patient do one of these treatments!"));?>
            </li>
        </ul>
        <br>
        <button class="btn btn-modal btn-default"><?=$this->translate(gettext("Close"));?></button>
    </div>
</div>

<div class="md-modal md-effect-1 col-md-2" id="modal-8">
    <div class="md-content md-content-red">
        <h3 style="color: white"><i class="fa fa-exclamation-triangle"></i> <?=$this->translate(gettext("Attention"));?></h3>
        <div>
            <ul class="RPS-UL">
            <li>
                <?=$this->translate(gettext("Don't do a treatment on pregnant woman! After breastfeeding wait two months!"));?>
            </li>
        </ul>
        <br>
        <button class="btn btn-modal btn-default"><?=$this->translate(gettext("Close"));?></button>
    </div>
</div>

<div class="md-modal md-effect-1 col-md-2" id="modal-9">
    <div class="md-content md-content-red">
        <h3 style="color: white"><i class="fa fa-exclamation-triangle"></i> <?=$this->translate(gettext("Attention"));?></h3>
        <div>
            <ul class="RPS-UL">
            <li>
                <?=$this->translate(gettext("Seek the agreement of her doctor if it dates back less than 2 years!"));?>
            </li>
        </ul>
        <br>
        <button class="btn btn-modal btn-default"><?=$this->translate(gettext("Close"));?></button>
    </div>
</div>

<div class="md-modal md-effect-1 col-md-2" id="modal-10">
    <div class="md-content md-content-red">
        <h3 style="color: white"><i class="fa fa-exclamation-triangle"></i> <?=$this->translate(gettext("Attention"));?></h3>
        <div>
            <ul class="RPS-UL">
            <li>
                <?=$this->translate(gettext("Do 2 joules below the basic skin type!"));?>
            </li>
        </ul>
        <br>
        <button class="btn btn-modal btn-default"><?=$this->translate(gettext("Close"));?></button>
    </div>
</div>

<div class="md-modal md-effect-1 col-md-2" id="modal-11">
    <div class="md-content md-content-red">
        <h3 style="color: white"><i class="fa fa-exclamation-triangle"></i> <?=$this->translate(gettext("Attention"));?></h3>
        <div>
            <ul class="RPS-UL">
            <li>
                <?=$this->translate(gettext("Caution: If \"YES\" answer to any of the questions above, delimit the area at risk and treat 2 cm of this area!"));?>
            </li>
        </ul>
        <br>
        <button class="btn btn-modal btn-default"><?=$this->translate(gettext("Close"));?></button>
    </div>
</div>


<div class="md-modal md-effect-1 col-md-2" id="modal-12">
    <div class="md-content md-content-red">
        <h3 style="color: white"><i class="fa fa-exclamation-triangle"></i> <?=$this->translate(gettext("Attention"));?></h3>
        <div>
            <ul class="RPS-UL">
            <li>
                <?=$this->translate(gettext("Please note, if significant inflammatory or varices, delineate the area at risk and treat 2 cm of this area!"));?>
            </li>
        </ul>
        <br>
        <button class="btn btn-modal btn-default"><?=$this->translate(gettext("Close"));?></button>
    </div>
</div>


    <div class="md-modal md-effect-1 col-md-2" id="modal-13">
        <div class="md-content md-content-red">
            <h3 style="color: white"><i class="fa fa-exclamation-triangle"></i> <?=$this->translate(gettext("Attention"));?></h3>
            <div>
                <ul class="RPS-UL">
                    <li>
                        <?=$this->translate(gettext("If there is a presence of allergens on the skin, please do a test 24H!"));?>
                    </li>
                </ul>
                <br>
                <button class="btn btn-modal btn-default" onclick="closeModal('modal-13')"><?=$this->translate(gettext("Close"));?></button>
            </div>
        </div>




        