<div class="modal fade" id="alert-age" tabindex="-1" role="dialog" aria-hidden="false" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title"><i class="fa fa-exclamation-triangle"></i> <?=$this->translate(gettext("Attention"));?></h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <h4>Some More data</h4>
                        <p>
                            <input id="name" name="name" type="text" placeholder="Your name" class="form-control">
                        </p>

                    </div>
                    <div class="col-md-6">
                        <h4>Some More data</h4>
                        <p>
                            <input id="name6" name="name" type="text" placeholder="Your name" class="form-control">
                        </p>

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn">Close</button>

            </div>
        </div>
    </div>
</div>

