<select id="select2-disabled-inputs-single" name="<?=$this->id;?>[]" class="form-control select2" placeholder="<?=$this->translate(gettext("Click to select"));?>" multiple>
    <option value="<?=$this->translate(gettext("Upper lip/Chin"));?>" zone="FACE"><?=$this->translate(gettext("Upper lip/Chin | FACE"));?></option>
    <option value="<?=$this->translate(gettext("Beard/Down Face"));?>" zone="FACE"><?=$this->translate(gettext("Beard/Down Face | FACE"));?></option>
    <option value="<?=$this->translate(gettext("Mustache"));?> zone="FACE"><?=$this->translate(gettext("Mustache | FACE"));?></option>
    <option value="<?=$this->translate(gettext("Cheek"));?>" zone="FACE"><?=$this->translate(gettext("Cheek | FACE"));?></option>
    <option value="<?=$this->translate(gettext("Neck"));?>" zone="FACE"><?=$this->translate(gettext("Neck | FACE"));?></option>
    <option value="<?=$this->translate(gettext("Nose or ear"));?>" zone="FACE"><?=$this->translate(gettext("Nose or ear | FACE"));?></option>
    <option value="<?=$this->translate(gettext("Inter eyebrows"));?>" zone="FACE"><?=$this->translate(gettext("Inter eyebrows | FACE"));?></option>
    <option value="<?=$this->translate(gettext("Hand or fingers"));?>" zone="ARM"><?=$this->translate(gettext("Hand or fingers  | ARM"));?></option>
    <option value="<?=$this->translate(gettext("Shoulders"));?>" zone="ARM"><?=$this->translate(gettext("Shoulders | ARM"));?></option>
    <option value="<?=$this->translate(gettext("Forearm"));?>" zone="ARM"><?=$this->translate(gettext("Forearm | ARM"));?></option>
    <option value="<?=$this->translate(gettext("Whole arms"));?>" zone="ARM"><?=$this->translate(gettext("Whole arms | ARM"));?></option>
    <option value="<?=$this->translate(gettext("Armpits"));?>" zone="ARM"><?=$this->translate(gettext("Armpits | ARM"));?></option>
    <option value="<?=$this->translate(gettext("Torso"));?>" zone="DOS/CHEST"><?=$this->translate(gettext("Torso | DOS/CHEST"));?></option>
    <option value="<?=$this->translate(gettext("Areola or nipple"));?>" zone="DOS/CHEST"><?=$this->translate(gettext("Areola or nipple | DOS/CHEST"));?></option>
    <option value="<?=$this->translate(gettext("Breasts"));?>" zone="DOS/CHEST"><?=$this->translate(gettext("Breasts | DOS/CHEST"));?></option>
    <option value="<?=$this->translate(gettext("Abdominal area"));?>" zone="DOS/CHEST"><?=$this->translate(gettext("Abdominal area | DOS/CHEST"));?></option>
    <option value="<?=$this->translate(gettext("Belly"));?>" zone="DOS/CHEST"><?=$this->translate(gettext("Belly | DOS/CHEST"));?></option>
    <option value="<?=$this->translate(gettext("Full Back"));?>" zone="DOS/CHEST"><?=$this->translate(gettext("Full Back | DOS/CHEST"));?></option>
    <option value="<?=$this->translate(gettext("Upper body"));?>" zone="DOS/CHEST"><?=$this->translate(gettext("Upper body | DOS/CHEST"));?></option>
    <option value="<?=$this->translate(gettext("Lower back"));?>" zone="DOS/CHEST"><?=$this->translate(gettext("Lower back | DOS/CHEST"));?></option>
    <option value="<?=$this->translate(gettext("Thighs"));?>" zone="THIGH/LEG/FOOT/PUBIS"><?=$this->translate(gettext("Thighs | THIGH/LEG/FOOT/PUBIS"));?></option>
    <option value="<?=$this->translate(gettext("Overflow thighs"));?>" zone="THIGH/LEG/FOOT/PUBIS"><?=$this->translate(gettext("Overflow thighs | THIGH/LEG/FOOT/PUBIS"));?></option>
    <option value="<?=$this->translate(gettext("Rear thighs"));?>" zone="THIGH/LEG/FOOT/PUBIS"><?=$this->translate(gettext("Rear thighs | THIGH/LEG/FOOT/PUBIS"));?></option>
    <option value="<?=$this->translate(gettext("Pubis"));?>" zone="THIGH/LEG/FOOT/PUBIS"><?=$this->translate(gettext("Pubis | THIGH/LEG/FOOT/PUBIS"));?></option>
    <option value="<?=$this->translate(gettext("Pubis + lip"));?>" zone="THIGH/LEG/FOOT/PUBIS"><?=$this->translate(gettext("Pubis + lip | THIGH/LEG/FOOT/PUBIS"));?></option>
    <option value="<?=$this->translate(gettext("Legs"));?>" zone="THIGH/LEG/FOOT/PUBIS"><?=$this->translate(gettext("Legs | THIGH/LEG/FOOT/PUBIS"));?></option>
    <option value="<?=$this->translate(gettext("Half legs"));?>" zone="THIGH/LEG/FOOT/PUBIS"><?=$this->translate(gettext("Half legs | THIGH/LEG/FOOT/PUBIS"));?></option>
    <option value="<?=$this->translate(gettext("Kneeling only"));?>" zone="THIGH/LEG/FOOT/PUBIS"><?=$this->translate(gettext("Kneeling only | THIGH/LEG/FOOT/PUBIS"));?></option>
    <option value="<?=$this->translate(gettext("Inter gluteal furrow"));?>" zone="THIGH/LEG/FOOT/PUBIS"><?=$this->translate(gettext("Inter gluteal furrow | THIGH/LEG/FOOT/PUBIS"));?></option>
    <option value="<?=$this->translate(gettext("Feet"));?>" zone="THIGH/LEG/FOOT/PUBIS"><?=$this->translate(gettext("Feet | THIGH/LEG/FOOT/PUBISt"));?></option>
    <option value="<?=$this->translate(gettext("Buttocks"));?>" zone="THIGH/LEG/FOOT/PUBIS"><?=$this->translate(gettext("Buttocks | THIGH/LEG/FOOT/PUBIS"));?></option>
</select>