<select id="select2-disabled-inputs-single" name="<?=$this->id;?>[]" class="form-control select2" placeholder="<?=$this->translate(gettext("Click to select"));?>" multiple>
    <option value="<?=$this->translate(gettext("Upper lip/Chin"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Upper lip/Chin")), $this->values);?>><?=$this->translate(gettext("Upper lip/Chin | FACE"));?></option>

    <option value="<?=$this->translate(gettext("Beard/Down Face"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Beard/Down Face")), $this->values);?>><?=$this->translate(gettext("Beard/Down Face | FACE"));?></option>

    <option value="<?=$this->translate(gettext("Mustache"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Mustache")), $this->values);?>><?=$this->translate(gettext("Mustache | FACE"));?></option>

    <option value="<?=$this->translate(gettext("Cheek"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Cheek")), $this->values);?>><?=$this->translate(gettext("Cheek | FACE"));?></option>

    <option value="<?=$this->translate(gettext("Neck"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Neck")), $this->values);?>><?=$this->translate(gettext("Neck | FACE"));?></option>

    <option value="<?=$this->translate(gettext("Nose or ear"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Nose or ear")), $this->values);?>><?=$this->translate(gettext("Nose or ear | FACE"));?></option>

    <option value="<?=$this->translate(gettext("Inter eyebrows"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Inter eyebrows")), $this->values);?>><?=$this->translate(gettext("Inter eyebrows | FACE"));?></option>

    <option value="<?=$this->translate(gettext("Hand or fingers"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Hand or fingers")), $this->values);?>><?=$this->translate(gettext("Hand or fingers  | ARM"));?></option>

    <option value="<?=$this->translate(gettext("Shoulders"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Shoulders")), $this->values);?>><?=$this->translate(gettext("Shoulders | ARM"));?></option>

    <option value="<?=$this->translate(gettext("Forearm"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Forearm")), $this->values);?>><?=$this->translate(gettext("Forearm | ARM"));?></option>

    <option value="<?=$this->translate(gettext("Whole arms"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Whole arms")), $this->values);?>><?=$this->translate(gettext("Whole arms | ARM"));?></option>

    <option value="<?=$this->translate(gettext("Armpits"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Armpits")), $this->values);?>><?=$this->translate(gettext("Armpits | ARM"));?></option>

    <option value="<?=$this->translate(gettext("Torso"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Torso")), $this->values);?>><?=$this->translate(gettext("Torso | DOS/CHEST"));?></option>

    <option value="<?=$this->translate(gettext("Areola or nipple"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Areola or nipple")), $this->values);?>><?=$this->translate(gettext("Areola or nipple | DOS/CHEST"));?></option>

    <option value="<?=$this->translate(gettext("Breasts"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Breasts")), $this->values);?>><?=$this->translate(gettext("Breasts | DOS/CHEST"));?></option>

    <option value="<?=$this->translate(gettext("Abdominal area"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Abdominal area")), $this->values);?>><?=$this->translate(gettext("Abdominal area | DOS/CHEST"));?></option>

    <option value="<?=$this->translate(gettext("Belly"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Belly")), $this->values);?>><?=$this->translate(gettext("Belly | DOS/CHEST"));?></option>

    <option value="<?=$this->translate(gettext("Full Back"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Full Back")), $this->values);?>><?=$this->translate(gettext("Full Back | DOS/CHEST"));?></option>

    <option value="<?=$this->translate(gettext("Upper body"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Upper body")), $this->values);?>><?=$this->translate(gettext("Upper body | DOS/CHEST"));?></option>

    <option value="<?=$this->translate(gettext("Lower back"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Lower back")), $this->values);?>><?=$this->translate(gettext("Lower back | DOS/CHEST"));?></option>

    <option value="<?=$this->translate(gettext("Thighs"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Thighs")), $this->values);?>><?=$this->translate(gettext("Thighs | THIGH/LEG/FOOT/PUBIS"));?></option>

    <option value="<?=$this->translate(gettext("Overflow thighs"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Overflow thighs")), $this->values);?>><?=$this->translate(gettext("Overflow thighs | THIGH/LEG/FOOT/PUBIS"));?></option>

    <option value="<?=$this->translate(gettext("Rear thighs"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Rear thighs")), $this->values);?>><?=$this->translate(gettext("Rear thighs | THIGH/LEG/FOOT/PUBIS"));?></option>

    <option value="<?=$this->translate(gettext("Pubis"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Pubis")), $this->values);?>><?=$this->translate(gettext("Pubis | THIGH/LEG/FOOT/PUBIS"));?></option>

    <option value="<?=$this->translate(gettext("Pubis + lip"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Pubis + lip")), $this->values);?>><?=$this->translate(gettext("Pubis + lip | THIGH/LEG/FOOT/PUBIS"));?></option>

    <option value="<?=$this->translate(gettext("Legs"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Legs")), $this->values);?>><?=$this->translate(gettext("Legs | THIGH/LEG/FOOT/PUBIS"));?></option>

    <option value="<?=$this->translate(gettext("Half legs"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Half legs")), $this->values);?>><?=$this->translate(gettext("Half legs | THIGH/LEG/FOOT/PUBIS"));?></option>

    <option value="<?=$this->translate(gettext("Kneeling only"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Kneeling only")), $this->values);?>><?=$this->translate(gettext("Kneeling only | THIGH/LEG/FOOT/PUBIS"));?></option>

    <option value="<?=$this->translate(gettext("Inter gluteal furrow"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Inter gluteal furrow")), $this->values);?>><?=$this->translate(gettext("Inter gluteal furrow | THIGH/LEG/FOOT/PUBIS"));?></option>

    <option value="<?=$this->translate(gettext("Feet"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Feet")), $this->values);?>><?=$this->translate(gettext("Feet | THIGH/LEG/FOOT/PUBISt"));?></option>

    <option value="<?=$this->translate(gettext("Buttocks"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("Buttocks")), $this->values);?>><?=$this->translate(gettext("Buttocks | THIGH/LEG/FOOT/PUBIS"));?></option>
</select>