<select id="select2-disabled-inputs-single" name="<?=$this->id;?>[]" class="form-control select2" placeholder="<?=$this->translate(gettext("Click to select"));?>" multiple>
    <option value="<?=$this->translate(gettext("Upper lip/Chin"));?>"><?=$this->translate(gettext("Upper lip/Chin | FACE"));?></option>
    <option value="<?=$this->translate(gettext("Beard/Down Face"));?>"><?=$this->translate(gettext("Beard/Down Face | FACE"));?></option>
    <option value="<?=$this->translate(gettext("Mustache"));?>"><?=$this->translate(gettext("Mustache | FACE"));?></option>
    <option value="<?=$this->translate(gettext("Cheek"));?>"><?=$this->translate(gettext("Cheek | FACE"));?></option>
    <option value="<?=$this->translate(gettext("Neck"));?>"><?=$this->translate(gettext("Neck | FACE"));?></option>
    <option value="<?=$this->translate(gettext("Nose or ear"));?>"><?=$this->translate(gettext("Nose or ear | FACE"));?></option>
    <option value="<?=$this->translate(gettext("Inter eyebrows"));?>"><?=$this->translate(gettext("Inter eyebrows | FACE"));?></option>
    <option value="<?=$this->translate(gettext("Hand or fingers"));?>"><?=$this->translate(gettext("Hand or fingers  | ARM"));?></option>
    <option value="<?=$this->translate(gettext("Shoulders"));?>"><?=$this->translate(gettext("Shoulders | ARM"));?></option>
    <option value="<?=$this->translate(gettext("Forearm"));?>"><?=$this->translate(gettext("Forearm | ARM"));?></option>
    <option value="<?=$this->translate(gettext("Whole arms"));?>"><?=$this->translate(gettext("Whole arms | ARM"));?></option>
    <option value="<?=$this->translate(gettext("Armpits"));?>"><?=$this->translate(gettext("Armpits | ARM"));?></option>
    <option value="<?=$this->translate(gettext("Torso"));?>"><?=$this->translate(gettext("Torso | DOS/CHEST"));?></option>
    <option value="<?=$this->translate(gettext("Areola or nipple"));?>"><?=$this->translate(gettext("Areola or nipple | DOS/CHEST"));?></option>
    <option value="<?=$this->translate(gettext("Breasts"));?>"><?=$this->translate(gettext("Breasts | DOS/CHEST"));?></option>
    <option value="<?=$this->translate(gettext("Abdominal area"));?>"><?=$this->translate(gettext("Abdominal area | DOS/CHEST"));?></option>
    <option value="<?=$this->translate(gettext("Belly"));?>"><?=$this->translate(gettext("Belly | DOS/CHEST"));?></option>
    <option value="<?=$this->translate(gettext("Full Back"));?>"><?=$this->translate(gettext("Full Back | DOS/CHEST"));?></option>
    <option value="<?=$this->translate(gettext("Upper body"));?>"><?=$this->translate(gettext("Upper body | DOS/CHEST"));?></option>
    <option value="<?=$this->translate(gettext("Lower back"));?>"><?=$this->translate(gettext("Lower back | DOS/CHEST"));?></option>
    <option value="<?=$this->translate(gettext("Thighs"));?>"><?=$this->translate(gettext("Thighs | THIGH/LEG/FOOT/PUBIS"));?></option>
    <option value="<?=$this->translate(gettext("Overflow thighs"));?>"><?=$this->translate(gettext("Overflow thighs | THIGH/LEG/FOOT/PUBIS"));?></option>
    <option value="<?=$this->translate(gettext("Rear thighs"));?>"><?=$this->translate(gettext("Rear thighs | THIGH/LEG/FOOT/PUBIS"));?></option>
    <option value="<?=$this->translate(gettext("Pubis"));?>"><?=$this->translate(gettext("Pubis | THIGH/LEG/FOOT/PUBIS"));?></option>
    <option value="<?=$this->translate(gettext("Pubis + lip"));?>"><?=$this->translate(gettext("Pubis + lip | THIGH/LEG/FOOT/PUBIS"));?></option>
    <option value="<?=$this->translate(gettext("Legs"));?>"><?=$this->translate(gettext("Legs | THIGH/LEG/FOOT/PUBIS"));?></option>
    <option value="<?=$this->translate(gettext("Half legs"));?>"><?=$this->translate(gettext("Half legs | THIGH/LEG/FOOT/PUBIS"));?></option>
    <option value="<?=$this->translate(gettext("Kneeling only"));?>"><?=$this->translate(gettext("Kneeling only | THIGH/LEG/FOOT/PUBIS"));?></option>
    <option value="<?=$this->translate(gettext("Inter gluteal furrow"));?>"><?=$this->translate(gettext("Inter gluteal furrow | THIGH/LEG/FOOT/PUBIS"));?></option>
    <option value="<?=$this->translate(gettext("Feet"));?>"><?=$this->translate(gettext("Feet | THIGH/LEG/FOOT/PUBISt"));?></option>
    <option value="<?=$this->translate(gettext("Buttocks"));?>"><?=$this->translate(gettext("Buttocks | THIGH/LEG/FOOT/PUBIS"));?></option>
</select>