<select id="select2-disabled-inputs-single" name="<?=$this->id;?>[]" class="form-control select2" placeholder="<?=$this->translate(gettext("Click to select"));?>" multiple>
    <option value="<?=$this->translate(gettext("FACE"));?>" <?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("FACE")), $this->values);?>><?=$this->translate(gettext("FACE"));?></option>
    <option value="<?=$this->translate(gettext("ARM"));?>"<?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("ARM")), $this->values);?>><?=$this->translate(gettext("ARM"));?></option>
    <option value="<?=$this->translate(gettext("DOS/CHEST"));?>"<?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("DOS/CHEST")), $this->values);?>><?=$this->translate(gettext("DOS/CHEST"));?></option>
    <option value="<?=$this->translate(gettext("THIGH/LEG/FOOT/PUBIS"));?>"<?=RPS_Aux_FormElements::multiSelect($this->translate(gettext("THIGH/LEG/FOOT/PUBIS")), $this->values);?>><?=$this->translate(gettext("THIGH/LEG/FOOT/PUBIS"));?></option>
</select>

