<select id="select2-disabled-inputs-single" name="<?=$this->id;?>[]" class="form-control select2" placeholder="<?=$this->translate(gettext("Click to select"));?>"  multiple>
<option value="<?=$this->translate(gettext("FACE"));?>"><?=$this->translate(gettext("FACE"));?></option>
    <option value="<?=$this->translate(gettext("ARM"));?>"><?=$this->translate(gettext("ARM"));?></option>
    <option value="<?=$this->translate(gettext("DOS/CHEST"));?>"><?=$this->translate(gettext("DOS/CHEST"));?></option>
    <option value="<?=$this->translate(gettext("THIGH/LEG/FOOT/PUBIS"));?>"><?=$this->translate(gettext("THIGH/LEG/FOOT/PUBIS"));?></option>
</select>