<div class="row">
	
	<div class="col-lg-12">
		
		<?php if (count($this->records) > 0): ?>
		
		<table class="table table-striped table-bordered table-advance table-hover">
			<thead>
				<tr>
					<th><i class="fa fa-calendar"></i> <?=$this->translate(gettext("Date"));?></th>
					<th><i class="fa fa-eye"></i> <?=$this->translate(gettext("View Appointment"));?></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->records as $record): ?>
					<tr>
						<td>
							<?=$record["date_app"];?>
						</td>
						<td>
							<a href="#" class="btn default btn-xs blue-stripe"><?=$this->translate(gettext("View"));?></a>
						</td>
					</tr>

				<?php endforeach; ?>
			</tbody>
			
		</table>
		
		<?php else: ?>

			<div class="alert alert-info alert-dismissable">
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
				<p><?=$this->translate(gettext("There are no appointments"));?></p>
			</div>
		
		<?php endif; ?>
	</div>
	
	
	
</div> 